spring:
  profiles:
    active:
      - service
      - local
  datasource:
    url: "jdbc:h2:file:./db/jataservice"
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
